### ISSUE TITLE
Contact page is not working

### ISSUE THREAD

**Issue by mixmixmix** [ChasNelson1990/chasnelson.co.uk#3]
**Impossible** to contact a creator of the website.

**Comment by ChasNelson1990** [comment]
It's all part of a cunning ploy @mixmixmix ! :-D
To be fixed shortly. What do you think would be best: a contact form? a list of contact methods, i.e. durham university address, email contacts? Link to my linkedIn contact options? Link to GitHub?
Suggestions welcome!

**Comment by mixmixmix** [comment]
All of the places on the internet where you can be found including spam@chasnelson.co.uk.
I personally don't like contact forms. Don't trust 'em.

**Comment by ChasNelson1990** [comment]
Added a contact page, what do you think?
