### ISSUE TITLE
Comments from mix #2

### ISSUE THREAD

**Issue by mixmixmix** [ChasNelson1990/chasnelson.co.uk#4]
1. I really like new icons which seem more 'gooey' (or maybe this is just me being tired).
2. The colour of links is offensively bright. Maybe make it less saturated but in bold font?
3. The sub-page title should be aligned vertically to the box.
   ![screenshot at 2016-05-13 21 09 17](https://cloud.githubusercontent.com/assets/9990867/15260567/716011e0-194f-11e6-9af2-1c3a76b6cc6c.png)

**Comment by ChasNelson1990** [comment]
@mixmixmix What do you think now? I've gone a bit darker overall, is it too dark? And the title is more vertically central.
